## Global Variabel
#@BaseUrl = https://pam-2026-p4-ifs18005-be.delcom.org:8080
#@BaseUrl = http://127.0.0.1:8000
@BaseUrl = https://pam-2026-p4-ifs23025-be.nieltobing.fun:8080

## Profile
## ===========================================

### Mengambil semua data tumbuhan
# @name GetProfile
GET {{BaseUrl}}/profile
Content-Type: application/json

### Mengambil photo profil
# @name GetProfilePhoto
GET {{BaseUrl}}/profile/photo
Content-Type: application/json


## Plants
## ===========================================

### Mengambil semua data tumbuhan
# @name GetAllPlants
GET {{BaseUrl}}/plants?search=
Content-Type: application/json

#> {%
#    client.global.set("plantId", response.body.data.plants[0].id);
#    console.log(client.global.get("plantId"))
#%}

### Menambahkan data tumbuhan baru
# @name PostPlants
POST {{BaseUrl}}/plants
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Kangkung
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("plantId", response.body.data.plantId);
    console.log(client.global.get("plantId"))
%}

### Mengambil data tumbuhan berdasarkan id-nya
# @name GetPlantById
GET {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json

### Melihat gambar tumbuhan
# @name GetPlantImageById
GET {{BaseUrl}}/plants/{{plantId}}/image
Content-Type: application/json

### Mengubah hanya data plant berdasarkan id-nya
# @name PutPlantOnlyData
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli Update
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary--

### Mengubah gambar dan data plant berdasarkan id-nya
# @name PutPlant
PUT {{BaseUrl}}/plants/{{plantId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Brokoli
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Brokoli adalah sayuran hijau yang kaya vitamin, mineral, dan serat
--WebAppBoundary
Content-Disposition: form-data; name="manfaat"

Membantu detoksifikasi dan menjaga kesehatan mata
--WebAppBoundary
Content-Disposition: form-data; name="efekSamping"

Dapat menyebabkan kembung
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

### Menghapus data plant berdasarkan id-nya
# @name DeletePlant
DELETE {{BaseUrl}}/plants/{{plantId}}
Content-Type: application/json


## ===========================================
## Sports
## ===========================================

### Mengambil semua data sport
# @name GetAllSports
GET {{BaseUrl}}/sports?search=
Accept: application/json

#> {%
#    client.global.set("sportId", response.body.data.sports[0].id);
#    console.log(client.global.get("sportId"))
#%}

### Menambahkan data sport baru
# @name PostSport
POST {{BaseUrl}}/sports
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Sepatu Lari X
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Sepatu lari ringan dan nyaman.
--WebAppBoundary
Content-Disposition: form-data; name="kelebihan"

Ringan dan tahan lama
--WebAppBoundary
Content-Disposition: form-data; name="teknologi_yang_digunkan"

Air Cushion Technology
--WebAppBoundary
Content-Disposition: form-data; name="Tenaga"

Manual
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

> {%
    client.global.set("sportId", response.body.data.sportId);
    console.log(client.global.get("sportId"));
%}

### Mengambil data sport berdasarkan id
# @name GetSportById
GET {{BaseUrl}}/sports/{{sportId}}
Accept: application/json

### Melihat gambar sport
# @name GetSportImageById
GET {{BaseUrl}}/sports/{{sportId}}/image
Accept: application/json

### Update data sport saja
# @name PutSportOnlyData
PUT {{BaseUrl}}/sports/{{sportId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Sepatu Lari Update
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Update deskripsi
--WebAppBoundary
Content-Disposition: form-data; name="kelebihan"

Update kelebihan
--WebAppBoundary
Content-Disposition: form-data; name="teknologi_yang_digunkan"

Update teknologi
--WebAppBoundary
Content-Disposition: form-data; name="Tenaga"

Manual
--WebAppBoundary--

### Update sport + gambar
# @name PutSport
PUT {{BaseUrl}}/sports/{{sportId}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="nama"

Sepatu Lari Final
--WebAppBoundary
Content-Disposition: form-data; name="deskripsi"

Final version
--WebAppBoundary
Content-Disposition: form-data; name="kelebihan"

Super ringan
--WebAppBoundary
Content-Disposition: form-data; name="teknologi_yang_digunkan"

Air Cushion Pro
--WebAppBoundary
Content-Disposition: form-data; name="Tenaga"

Manual
--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="example.png"
Content-Type: image/png

< ./example.png
--WebAppBoundary--

### Hapus sport
# @name DeleteSport
DELETE {{BaseUrl}}/sports/{{sportId}}
Accept: application/json